print("Qual é o seu aniversário?")
dia_aniversario = input ("Digite o dia")
print(dia_aniversario)
print ("O dia é", dia_aniversario)
mes_aniversario = input ("Digite o mês")
print(mes_aniversario)
print("O mês é", mes_aniversario)
ano_aniversario = input ("Digite o ano")
print(ano_aniversario)
print("O ano é", ano_aniversario)
print ("Seu aniversário é", dia_aniversario, "de", mes_aniversario, "de", ano_aniversario)
