a = float (input("Escreva o primeiro valor: "))
print(a)
b = float (input("Escreva o segundo valor: "))
print (a, "-", b)
c = float (input("Escreva o terceiro valor: "))
print (a, "-", b, "x", c)
d = float (input("Escreva o quarto valor: "))
print (a, "-", b, "x", c, "**", d)
e = float (input("Escreva o quinto valor: "))
print (a, "-", b, "x", c, "**", d, "%", e)
f = (a-b*c**d%e)
print ("O valor será:"a, "-", b, "x", c, "**", d, "%", e, "=", f)
